### ISSUE TITLE
GG Cheats

### ISSUE THREAD

**Issue by louikwar** [QuietArtX/QuietArtx-TBColorBot#1]
just check the python code and u will notice

**Comment by skullcheat** [comment]
True 10000%%%%%%%%% encrypted file.
HAHAHA RATTt report this account

**Comment by QuietArtX** [comment]
> True 10000%%%%%%%%% encrypted file. HAHAHA RATTt report this account

u r stupid ?  hahahah , VERY STUPID PEOPLE
if you want to cheat, buy it don't want it for free, want the source code for free hahah, you are very stupid
